### ISSUE TITLE
Update node version

### ISSUE THREAD

**Issue by adeelamin15** [Reggionick/s3-deploy#106]
Github actions for Node 12 are being deprecated and will be replaced by Node 16 one.  Lets upgrade the node version to Node 16.

[Github Announcement](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/)

```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: reggionick/s3-deploy
```

**Comment by vhnam** [comment]
@Reggionick can you merge my PR?
https://github.com/Reggionick/s3-deploy/pull/115

**Comment by coliff** [comment]
I think this issue can be closed now since PR 115 is merged.
