### ISSUE TITLE
delete-removed not working

### ISSUE THREAD

**Issue by TheMechanic** [Reggionick/s3-deploy#12]
Hi,
I have an issue with this plugin : 
event with delete-removed set to true, files are not deleted, I have to do it manually. For example app.1234.js stay here, even after the plugin push the new version app.5678.js. Of the app.1234.js is not in the folder I push.
The key/secret I use has full rights access to s3. Anyone knows what could do this ?

many thanks

**Comment by Reggionick** [comment]
Fixed in [v3](https://github.com/Reggionick/s3-deploy/releases/tag/v3.0.0)
