### ISSUE TITLE
Tag versions

### ISSUE THREAD

**Issue by EdieLemoine** [Reggionick/s3-deploy#144]
Hi, we're using your action at @myparcelnl but you haven't updated the v3 tag or pushed new tags since v3.2.0. The latest tagged version is still on Node 12 which logs deprecation warnings. I don't want to use action@master, maybe you could tag a new version?

In case you're looking to automate versioning of your action(s), we have an action for it: [myparcelnl/actions/update-tags@v3](https://github.com/myparcelnl/actions#update-tags)

**Comment by Reggionick** [comment]
Hi @EdieLemoine! Yes we should release a new version (4.0.0) with all the changes made after the last version tag. Right now I cannot work on it, but any help is appreciated

**Comment by afh** [comment]
@Reggionick, can you outline how folks could help out to get a new version released?For example what are open issues or tasks that need doing prior to the release (would be nice to see those tagged with a milestone)?

**Comment by grudelsud** [comment]
hey @Reggionick I have the same problem, using this package (thanks for making it available!) but receiving warnings for Node 12. Which apparently will be moved to 16 "by Summer 2023" according to: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

what is the help you are looking for?

**Comment by Reggionick** [comment]
Hi all! I've created the [v4.0.0](https://github.com/Reggionick/s3-deploy/tree/v4.0.0) release with the changes ready to be released.

I think the next step to resolve the deprecated dependencies are:

1. Integrate the `import-io/s3-deploy` dependency
2. Upgrade the `aws-sdk` dependency (with needed changes)

What do you think? (Maybe we can open a discussion for that)

**Comment by coliff** [comment]
> What do you think? (Maybe we can open a discussion for that)

Yes, I think we can continue that conversation in issue #146
