### ISSUE TITLE
No cache-control parameter

### ISSUE THREAD

**Issue by norman-ags** [Reggionick/s3-deploy#156]
Hi! How do we add `Cache-Control: no-cache`? There is `noCache` parameter but it adds `no-store` and `must-revalidate` which is not good in all use cases. Looking at s3-deploy@1.4.0, they have --cacheControl parameter for custom use cases. Maybe we can add a cacheControl parameter?

**Comment by oeed** [comment]
On a similar note, it'd also be helpful specify no cache for specific files only. For example, I don't want `index.html` cached,  but I want all other files cached.
