### ISSUE TITLE
add --private flag for S3 static website hosting

### ISSUE THREAD

**Issue by zzikkzzakk** [Reggionick/s3-deploy#16]
According to 
https://github.com/import-io/s3-deploy/issues/33#issuecomment-462415575
the --private flag of s3-deploy is needed if files should be uploaded to S3 buckets with static website hosting enabled
Otherwise a `Upload error: AccessDenied: Access Denied` happens.

**Comment by arascheuski** [comment]
We have the same issue when turn all "Block public access" in AWS S3 bucket permissions settings. 
Please add fix, for ex.:
```
                        --bucket ${bucket} \
                        --region ${bucketRegion} \
                        --cwd . \
                        --distId ${distId} \
                        --etag \
                        --gzip xml,html,htm,js,css,ttf,otf,svg,txt \
                        --invalidate "${invalidation}" \
                        --noCache \
                        --private \
                        ${deleteRemovedArg} `;
```
Sorry, I don`t have permissions to do PR to your repo.

**Comment by Reggionick** [comment]
Fixed in [v3](https://github.com/Reggionick/s3-deploy/releases/tag/v3.0.0)
