### ISSUE TITLE
Incorrect documentation for the files-included 

### ISSUE THREAD

**Issue by rkhaslarov** [Reggionick/s3-deploy#181]
In the docs, we see comma separated glob options it which is completely incorrect, correct one should be OR condition like:
`files-to-include: '{.*/**,**}'`

**Comment by gustavoiha** [comment]
That is what my setup was missing, thank you!

**Comment by super-macha** [comment]
agreed with the recommendation. Current glob pattern resulted in not copying any files to S3.

**Comment by rkhaslarov** [comment]
Thanks guys!
