### ISSUE TITLE
Build failed using example workflow

### ISSUE THREAD

**Issue by Phunky** [Reggionick/s3-deploy#2]
Hi,

I've taken the example workflow and looked to deploy it on my repo but had the following error.

`
Error: Cannot find module '/home/runner/work/markharwood.info/markharwood.info/node_modules/s3-deploy/bin/s3-deploy'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
`

**Comment by Reggionick** [comment]
Hi @Phunky,

I think you haven't added `s3-deploy` package to your project. Could you check?

(Maybe I should add this to the documentation)

**Comment by Phunky** [comment]
Aha, I actually was planning on doing that as a fallback :D but think that dependency would be expected to be handled by the action your pulling in.

**Comment by Reggionick** [comment]
I think you're right. This dependency should be handled by the action! I'll check this.

**Comment by Reggionick** [comment]
I've published a new version (v1.1). This should works without specific dependencies!

Let me now

**Comment by Phunky** [comment]
I'll give it a go now.

**Comment by Phunky** [comment]
Looks like the dependency is fixed, however it looks like it's not picking up the bucket name when attempting to upload.

<img width="2032" alt="image" src="https://user-images.githubusercontent.com/67351/84794397-181f4080-afee-11ea-8730-3359836de792.png">

**Comment by Reggionick** [comment]
D'oh!
The v1.1.1 should be the one!

**Comment by Phunky** [comment]
It's no longer causing any errors, however nothing is now uploading but I suspect thats something on my end...

**Comment by Reggionick** [comment]
Ok, let me now!

**Comment by diegoarcega** [comment]
hey, I'm also having this issue, nothing is updating on s3.
I run the action on github, nothing happens, when I run my local script with aws cli, it works.

**Comment by Reggionick** [comment]
Closing this in favor of #3
