### ISSUE TITLE
failed on npx

### ISSUE THREAD

**Issue by saviour123** [Reggionick/s3-deploy#25]
This throws an error about npx not found. 
```Error: There was an error when attempting to execute the process '/usr/local/bin/npx'. This may indicate the process failed to start. Error: spawn /usr/local/bin/npx ENOENT```

**Comment by Reggionick** [comment]
Hi @saviour123, is this the same issue of #24?

**Comment by saviour123** [comment]
@Reggionick Same issue.

**Comment by kees-** [comment]
For what it's worth, I think I was also getting this by forgetting to check out the repo.

Not sure if it's the same cause of the error for others. Posting this if it helps solve a rookie gotcha. Each yml posted in #13 also lacked the checkout step.

```yaml
steps:
  - uses: actions/checkout@v3
  - ...
```

Immediately zapped the error in OP
