### ISSUE TITLE
Not uploading files

### ISSUE THREAD

**Issue by diegoarcega** [Reggionick/s3-deploy#3]
I'm not sure if it is not uploading the files or the files are just not being updated. 

I run the action on github, nothing happens (it was working before), when I run my local script with the aws cli I have, it works.

using this:  reggionick/s3-deploy@v1

**Comment by Reggionick** [comment]
Issue fixed in version [1.1.2](https://github.com/Reggionick/s3-deploy/releases/tag/v1.1.2)
