### ISSUE TITLE
expire multiple dist ids at the same time

### ISSUE THREAD

**Issue by krtschmr** [Reggionick/s3-deploy#94]
we have a quite complex subdomain logic and thus multiple distributions that we need to expire while deploying or build.
there is no `distribution-ids: ["1", "2", "3"]` which could have been handy. 

is there a downside to supporting such argument?
i saw that internally, the call goes to `deploy` which then takes only one distribution-id. how to handle it from there?

**Comment by Reggionick** [comment]
I think that the module used under the hood ([package/s3-deploy](https://www.npmjs.com/package/s3-deploy)) doesn't support this.

Furthermore the source code is no more available on GH and it's not easily analysable. In the part I wrote to the maintainers if we could integrate that code into this action, but I've received no answer and it still an open point
